title        : "pk11.us"
description  : "Pk11's site"
repo         : "Epicpkmn11/pk11.us"
color        : "#f2acae"
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html"
include      : [".well-known"]

defaults:
  - values:
      layout: "default"
      title: "Pk11"

plugins:
  - "jekyll-github-metadata"